# Generated by Django 5.1.5 on 2025-01-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
