# Generated by Django 5.1.5 on 2025-02-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_atributorevisar_maquinaequipo_persona_rol_ubicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='maquina_equipo',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='recurso',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurso',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
