# Generated by Django 5.1.5 on 2025-06-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contacto_ejecucionrpa_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecucionrpa',
            name='mensajes_enviados',
        ),
        migrations.AddField(
            model_name='ejecucionrpa',
            name='cantidad_enviados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ejecucionrpa',
            name='cantidad_fallidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ejecucionrpa',
            name='cantidad_objetivo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejecucionrpa',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ejecucionrpa',
            name='fecha_ejecucion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
