# Generated by Django 5.1.5 on 2025-06-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_campaña'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaña',
            new_name='Campana',
        ),
    ]
