# Generated by Django 5.1.5 on 2025-06-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_campaña_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cargo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contacto',
            name='industria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
