# Generated by Django 5.1.5 on 2025-06-28 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contacto_cargo_contacto_industria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('error_envio', models.BooleanField(default=False)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='base.campana')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='base.contacto')),
            ],
        ),
    ]
