# Generated by Django 5.1.5 on 2025-06-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_iniciativa_fase_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='color_hex',
            field=models.CharField(default='#cccccc', max_length=7),
        ),
        migrations.AddField(
            model_name='fase',
            name='icono',
            field=models.CharField(default='📌', max_length=5),
        ),
    ]
