# Generated by Django 5.1.5 on 2025-06-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_fase_color_hex_fase_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_completada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
