# Generated by Django 5.1.5 on 2025-07-02 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_tarea_fecha_completada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='Frase o nota significativa del hito')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='hitos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='base.tarea')),
            ],
        ),
    ]
