# Generated by Django 5.1.5 on 2025-07-02 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_hito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('llamada', '📞 Llamada de reclutador'), ('entrevista_agendada', '🗓️ Entrevista agendada'), ('entrevista_realizada', '✅ Entrevista realizada'), ('oferta', '🎉 Oferta recibida')], max_length=30)),
                ('empresa', models.CharField(max_length=100)),
                ('fecha_evento', models.DateField()),
                ('comentario', models.TextField(blank=True)),
                ('mostrar_en_feed', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
