# Generated by Django 5.1.5 on 2025-07-03 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_eventoagenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HitoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contacto', 'Contacto inicial'), ('test_psico', 'Test psicológico'), ('entrevista_1', 'Entrevista 1'), ('entrevista_2', 'Entrevista 2'), ('entrevista_3', 'Entrevista 3'), ('fin_proceso', 'Fin del proceso'), ('resultado', 'Resultado / Feedback')], max_length=20)),
                ('fecha', models.DateField()),
                ('comentario', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='base.procesoseleccion')),
            ],
        ),
    ]
