# Generated by Django 5.1.5 on 2025-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_procesoseleccion_hitoproceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoseleccion',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=20),
        ),
    ]
