# Generated by Django 5.1.5 on 2025-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_procesoseleccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoseleccion',
            name='comentario_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procesoseleccion',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procesoseleccion',
            name='resultado',
            field=models.CharField(blank=True, choices=[('positivo', 'Seleccionado'), ('negativo', 'No seleccionado')], max_length=30, null=True),
        ),
    ]
