# Generated by Django 5.1.5 on 2025-07-11 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_procesoseleccion_comentario_final_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoagenda',
            name='tipo_evento',
            field=models.CharField(choices=[('llamada', '📞 Llamada de reclutador'), ('entrevista_agendada', '🗓️ Entrevista agendada'), ('entrevista_realizada', '✅ Entrevista realizada'), ('oferta', '🎉 Oferta recibida'), ('avance', '👈Evento de avance')], max_length=30),
        ),
        migrations.CreateModel(
            name='PublicacionFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='feed_imagenes/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('animo', models.ManyToManyField(blank=True, related_name='reaccion_animo', to=settings.AUTH_USER_MODEL)),
                ('felicidades', models.ManyToManyField(blank=True, related_name='reaccion_felicidades', to=settings.AUTH_USER_MODEL)),
                ('fuerza', models.ManyToManyField(blank=True, related_name='reaccion_fuerza', to=settings.AUTH_USER_MODEL)),
                ('me_gusta', models.ManyToManyField(blank=True, related_name='reaccion_me_gusta', to=settings.AUTH_USER_MODEL)),
                ('tu_puedes', models.ManyToManyField(blank=True, related_name='reaccion_tu_puedes', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
