# Generated by Django 5.1.5 on 2025-07-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_eventoagenda_tipo_evento_publicacionfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fase',
            name='fecha_objetivo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fase',
            name='publicado_en_feed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fase',
            name='reflexion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
