# Generated by Django 5.1.5 on 2025-07-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_fase_completado_fase_fecha_objetivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoLinkedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('perfil_linkedin', models.URLField()),
                ('open_to_work', models.BooleanField(default=False)),
            ],
        ),
    ]
