# Generated by Django 5.1.5 on 2025-08-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_contactolinkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
