# Generated by Django 5.1.5 on 2025-08-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_tarea_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='etapa_ventas',
            field=models.CharField(choices=[('inicial', 'Mensaje enviado'), ('respondido', 'Respondió mensaje'), ('reunion_agendada', 'Reunión agendada'), ('negociacion', 'En negociación'), ('cerrado', 'Cerrado')], default='inicial', max_length=30),
        ),
    ]
