# Generated by Django 5.1.5 on 2025-08-30 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_contacto_etapa_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField()),
                ('tipo_cierre', models.CharField(max_length=50)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('responsable', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='base.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_anterior', models.CharField(choices=[('inicial', 'Mensaje enviado'), ('respondido', 'Respondió mensaje'), ('reunion_agendada', 'Reunión agendada'), ('negociacion', 'En negociación'), ('cerrado', 'Cerrado')], max_length=30)),
                ('etapa_nueva', models.CharField(choices=[('inicial', 'Mensaje enviado'), ('respondido', 'Respondió mensaje'), ('reunion_agendada', 'Reunión agendada'), ('negociacion', 'En negociación'), ('cerrado', 'Cerrado')], max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_etapas', to='base.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensaje', 'Mensaje'), ('respuesta', 'Respuesta'), ('reunion', 'Reunión'), ('llamada', 'Llamada'), ('seguimiento', 'Seguimiento'), ('otro', 'Otro')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='base.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('fecha_envio_propuesta', models.DateTimeField()),
                ('monto_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documentos_adjuntos', models.TextField(blank=True)),
                ('estado', models.CharField(max_length=100)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitaciones', to='base.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='PostVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('nivel_satisfaccion', models.IntegerField(blank=True, null=True)),
                ('comentarios_cliente', models.TextField(blank=True)),
                ('acciones_realizadas', models.TextField(blank=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postventas', to='base.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('modalidad', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
                ('resumen', models.TextField(blank=True)),
                ('resultado', models.CharField(blank=True, max_length=100)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='base.contacto')),
            ],
        ),
    ]
