# Generated by Django 5.1.5 on 2025-09-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_cierre_historialetapa_interaccion_licitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hito',
            name='carga',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carga utilizada (kg)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hito',
            name='repeticiones',
            field=models.PositiveIntegerField(blank=True, help_text='Número de repeticiones por serie', null=True),
        ),
        migrations.AddField(
            model_name='hito',
            name='series',
            field=models.PositiveIntegerField(blank=True, help_text='Número de series realizadas', null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='etapa_ventas',
            field=models.CharField(choices=[('contacto', 'Contacto'), ('reunion', 'Reunión'), ('licitacion', 'Licitación'), ('cierre', 'Cierre'), ('postventa', 'PostVenta')], default='contacto', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialetapa',
            name='etapa_anterior',
            field=models.CharField(choices=[('contacto', 'Contacto'), ('reunion', 'Reunión'), ('licitacion', 'Licitación'), ('cierre', 'Cierre'), ('postventa', 'PostVenta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historialetapa',
            name='etapa_nueva',
            field=models.CharField(choices=[('contacto', 'Contacto'), ('reunion', 'Reunión'), ('licitacion', 'Licitación'), ('cierre', 'Cierre'), ('postventa', 'PostVenta')], max_length=30),
        ),
    ]
