# Generated by Django 5.1.5 on 2026-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_hito_carga_hito_repeticiones_hito_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativa',
            name='categoria_maternal',
            field=models.CharField(choices=[('hogar', 'Hogar y Logística'), ('crianza', 'Crianza y Desarrollo'), ('trabajo', 'Trabajo y Proyectos'), ('vinculos', 'Vínculos y Relaciones'), ('salud', 'Salud Mental y Emocional')], default='hogar', max_length=20),
        ),
    ]
