# Generated by Django 5.1.5 on 2026-02-06 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_iniciativa_categoria_maternal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedApoyoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('codigo_acceso', models.CharField(max_length=20, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_apoyo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='delegado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_delegadas', to='base.redapoyouser'),
        ),
    ]
