# Generated by Django 5.1.5 on 2026-09-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_redapoyouser_tarea_delegado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='categoria_maternal',
            field=models.CharField(choices=[('hogar', 'Agendamiento y Recepción'), ('crianza', 'Control de stock e inventario'), ('trabajo', 'Preparación de pedidos y despacho'), ('vinculos', 'Mantenimiento'), ('salud', 'Calidad')], default='hogar', max_length=20),
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('capturada', 'Capturada'), ('procesando', 'En procesamiento'), ('convertida', 'Convertida'), ('archivada', 'Archivada'), ('descartada', 'Descartada')], default='capturada', max_length=20)),
                ('etiquetas', models.CharField(blank=True, help_text='Separadas por coma. Ejemplo: logística, app, automatización', max_length=255)),
                ('energia', models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fase_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas_origen', to='base.fase')),
                ('iniciativa_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas_origen', to='base.iniciativa')),
                ('tarea_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas_origen', to='base.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
